### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by sdipietro** [useNavigate/Zelp#2]
# Feature List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Render, and Production README.
    - [x] The other 4 are from the MVP List or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

**Comment by sdipietro** [comment]
4 additional features should be from pre-approved list (see a/A open). Should have description of the app. Should be formatted correctly (see bluebird)

**Comment by sdipietro** [comment]
Production README should be seventh feature. Bonus should be last. Business page should be first feature you work on after auth.

**Comment by useNavigate** [comment]
thank you so much for the quick feed back!
